export const AZPIEUSKALKI_TOWNS = {
  "ekialde-nafarra": [
    "Bidankoze",
    "Burgi",
    "Erronkari",
    "Espartza\u002DZaraitzu",
    "Ezkaroze",
    "Galoze",
    "Garde",
    "Gorza",
    "Itzaltzu",
    "Izaba",
    "Jaurrieta",
    "Orontze",
    "Otsagabia",
    "Sartze",
    "Urzainki",
    "Uztarroze"
  ],
  "erdialde-sartaldea": [
    "Abaltzisketa",
    "Aduna",
    "Aia",
    "Aizarnazabal",
    "Albiztur",
    "Alegia",
    "Alkiza",
    "Altzaga",
    "Altzo",
    "Amasa\u002DVillabona",
    "Amezketa",
    "Andoain",
    "Anoeta",
    "Arama",
    "Asteasu",
    "Astigarraga",
    "Ataun",
    "Azkoitia",
    "Azpeitia",
    "Baliarrain",
    "Beasain",
    "Beizama",
    "Belauntza",
    "Berastegi",
    "Berrobi",
    "Bidania\u002DGoiatz",
    "Donostia",
    "Elduain",
    "Errezil",
    "Ezkio\u002DItsaso",
    "Gabiria",
    "Gaintza",
    "Gaztelu",
    "Getaria",
    "Hernani",
    "Hernialde",
    "Ibarra",
    "Idiazabal",
    "Ikaztegieta",
    "Irura",
    "Itsasondo",
    "Larraul",
    "Lasarte\u002DOria",
    "Lazkao",
    "Leaburu",
    "Legazpi",
    "Legorreta",
    "Lizartza",
    "Mutiloa",
    "Olaberria",
    "Ordizia",
    "Orendain",
    "Orexa",
    "Orio",
    "Ormaiztegi",
    "Segura",
    "Tolosa",
    "Urnieta",
    "Urretxu",
    "Usurbil",
    "Zaldibia",
    "Zarautz",
    "Zegama",
    "Zerain",
    "Zestoa",
    "Zizurkil",
    "Zumaia",
    "Zumarraga"
  ],
  "erdialde-sortaldea": [
    "Araitz",
    "Arano",
    "Areso",
    "Basaburua",
    "Betelu",
    "Errenteria",
    "Goizueta",
    "Hondarribia",
    "Imotz",
    "Irun",
    "Larraun",
    "Leitza",
    "Lekunberri",
    "Lezo",
    "Oiartzun",
    "Pasaia"
  ],
  "mendebal-sartaldea": [
    "Amurrio",
    "Arakaldo",
    "Arantzazu",
    "Areatza",
    "Arrankudiaga",
    "Arrieta",
    "Arrigorriaga",
    "Artea",
    "Bakio",
    "Barrika",
    "Basauri",
    "Bedia",
    "Berango",
    "Bilbo",
    "Derio",
    "Dima",
    "Etxebarri",
    "Fruiz",
    "Galdakao",
    "Gamiz\u002DFika",
    "Gatika",
    "Getxo",
    "Gorliz",
    "Igorre",
    "Larrabetzu",
    "Laudio",
    "Laukiz",
    "Lemoa",
    "Lemoiz",
    "Lezama",
    "Loiu",
    "Maruri\u002DJatabe",
    "Meñaka",
    "Mungia",
    "Orozko",
    "Plentzia",
    "Sondika",
    "Sopela",
    "Ugao",
    "Urduliz",
    "Zamudio",
    "Zaratamo",
    "Zeanuri",
    "Zeberio"
  ],
  "mendebal-sortaldea": [
    "Abadiño",
    "Ajangiz",
    "Amorebieta\u002DEtxano",
    "Amoroto",
    "Antzuola",
    "Aramaio",
    "Aretxabaleta",
    "Arrasate",
    "Arratzu",
    "Arratzua\u002DUbarrundia",
    "Atxondo",
    "Aulesti",
    "Bergara",
    "Bermeo",
    "Berriatua",
    "Berriz",
    "Busturia",
    "Deba",
    "Durango",
    "Ea",
    "Eibar",
    "Elantxobe",
    "Elgeta",
    "Elgoibar",
    "Elorrio",
    "Ereño",
    "Ermua",
    "Errigoiti",
    "Eskoriatza",
    "Etxebarria",
    "Forua",
    "Garai",
    "Gautegiz\u002DArteaga",
    "Gernika\u002DLumo",
    "Gizaburuaga",
    "Ibarrangelu",
    "Ispaster",
    "Iurreta",
    "Izurtza",
    "Kortezubi",
    "Legutio",
    "Leintz Gatzaga",
    "Lekeitio",
    "Mallabia",
    "Markina\u002DXemein",
    "Mañaria",
    "Mendaro",
    "Mendata",
    "Mendexa",
    "Morga",
    "Mundaka",
    "Munitibar\u002DArbatzegi\u002DGerrikaitz",
    "Murueta",
    "Mutriku",
    "Muxika",
    "Nabarniz",
    "Ondarroa",
    "Otxandio",
    "Oñati",
    "Soraluze",
    "Sukarrieta",
    "Ubide",
    "Zaldibar",
    "Zigoitia",
    "Ziortza\u002DBolibar",
    "Zuia"
  ],
  "nafar-erdigunea": [
    "Anue",
    "Arakil",
    "Artzibar",
    "Atetz",
    "Berriozar",
    "Ezkabarte",
    "Irañeta",
    "Irurtzun",
    "Itza",
    "Lantz",
    "Odieta",
    "Olaibar",
    "Txulapain",
    "Uharte\u002DArakil",
    "Ultzama"
  ],
  "nafar-hego-sartaldea": [
    "Altsasu",
    "Arbizu",
    "Arruazu",
    "Bakaiku",
    "Ergoiena",
    "Etxarri Aranatz",
    "Iturmendi",
    "Lakuntza",
    "Olatzagutia",
    "Urdiain",
    "Ziordia"
  ],
  "nafar-ipar-sartaldea": [
    "Arantza",
    "Bera",
    "Bertizarana",
    "Donamaria",
    "Doneztebe",
    "Elgorriaga",
    "Eratsun",
    "Etxalar",
    "Ezkurra",
    "Igantzi",
    "Ituren",
    "Labaien",
    "Lesaka",
    "Oitz",
    "Saldias",
    "Sunbilla",
    "Urroz",
    "Zubieta"
  ],
  "nafar-sortaldea": [
    "Abaurregaina",
    "Abaurrepea",
    "Aria",
    "Aribe",
    "Auritz",
    "Baztan",
    "Erroibar",
    "Esteribar",
    "Garaioa",
    "Garralda",
    "Hiriberri",
    "Orbaizeta",
    "Orbara",
    "Orreaga"
  ],
  "naflap-sartaldea": [
    "Ahetze",
    "Ainhoa",
    "Aldude",
    "Angelu",
    "Anhauze",
    "Arbona",
    "Arrangoitze",
    "Arrosa",
    "Azkaine",
    "Azkarate",
    "Baigorri",
    "Baiona",
    "Banka",
    "Basusarri",
    "Biarritz",
    "Bidarrai",
    "Bidarte",
    "Biriatu",
    "Bokale",
    "Donibane Lohizune",
    "Ezpeleta",
    "Getaria (L)",
    "Haltsu",
    "Hendaia",
    "Hiriburu",
    "Irulegi",
    "Itsasu",
    "Jatsu",
    "Kanbo",
    "Larresoro",
    "Lasa",
    "Lehuntze",
    "Luhuso",
    "Luzaide",
    "Milafranga",
    "Mugerre",
    "Ortzaize",
    "Sara",
    "Senpere",
    "Urdazubi",
    "Urepele",
    "Urketa",
    "Urruña",
    "Uztaritze",
    "Ziburu",
    "Zugarramurdi",
    "Zuraide"
  ],
  "naflap-sortaldea": [
    "Ahatsa\u002DAltzieta\u002DBazkazane",
    "Ahurti",
    "Aiherra",
    "Ainhize\u002DMonjolose",
    "Aintzila",
    "Aiziritze\u002DGamue\u002DZohazti",
    "Akamarre",
    "Amendüze\u002DUnaso",
    "Amorotze\u002DZokotze",
    "Arberatze\u002DZilhekoa",
    "Arboti\u002DZohota",
    "Arhantsusi",
    "Armendaritze",
    "Arnegi",
    "Arrueta\u002DSarrikota",
    "Bardoze",
    "Bastida",
    "Behaskane\u002DLaphizketa",
    "Behauze",
    "Behorlegi",
    "Beskoitze",
    "Bidaxune",
    "Bithiriña",
    "Bunuze",
    "Burgue\u002DErreiti",
    "Buztintze\u002DHiriberri",
    "Donaixti\u002DIbarre",
    "Donamartiri",
    "Donapaleu",
    "Donazaharre",
    "Donibane Garazi",
    "Donoztiri",
    "Duzunaritze\u002DSarasketa",
    "Eiheralarre",
    "Erango",
    "Etxarri",
    "Ezterenzubi",
    "Gabadi",
    "Gamarte",
    "Garrüze",
    "Gixune",
    "Hazparne",
    "Heleta",
    "Hozta",
    "Ibarrola",
    "Iholdi",
    "Ilharre",
    "Irisarri",
    "Izpura",
    "Izturitze",
    "Izura\u002DAzme",
    "Jatsu Garazi",
    "Jutsi",
    "Labetze\u002DBizkai",
    "Lakarra",
    "Landibarre",
    "Larribarre\u002DSorhapürü",
    "Larzabale\u002DArroze\u002DZibitze",
    "Lekorne",
    "Lekuine",
    "Lekunberri (NB)",
    "Lüküze\u002DAltzümarta",
    "Makea",
    "Martxueta",
    "Mehaine",
    "Mendibe",
    "Oragarre",
    "Ostankoa",
    "Samatze",
    "Suhuskune",
    "Uharte Garazi",
    "Uhartehiri",
    "Zaro"
  ],
  "zuberera": [
    "Ainharbe",
    "Aloze\u002DZiboze\u002DOnizegaine",
    "Altzai\u002DAltzabeheti\u002DZunharreta",
    "Altzürükü",
    "Arrokiaga",
    "Arüe\u002DIthorrotze\u002DOlhaibi",
    "Atharratze\u002DSorholüze",
    "Barkoxe",
    "Berrogaine\u002DLarüntze",
    "Bildoze\u002DOnizepea",
    "Domintxaine\u002DBerroeta",
    "Eskiula",
    "Etxebarre",
    "Ezpeize\u002DÜndüreine",
    "Gamere\u002DZihiga",
    "Garindaine",
    "Gotaine\u002DIrabarne",
    "Hauze",
    "Idauze\u002DMendi",
    "Iruri",
    "Jeztaze",
    "Lakarri\u002DArhane\u002DSarrikotagaine",
    "Larraine",
    "Lexantzü\u002DZunharre",
    "Ligi\u002DAtherei",
    "Liginaga\u002DAstüe",
    "Lohitzüne\u002DOihergi",
    "Maule\u002DLextarre",
    "Mendikota",
    "Mitikile\u002DLarrori\u002DMendibile",
    "Montori\u002DBerorize",
    "Muskildi",
    "Ospitalepea",
    "Ozaraine\u002DErribareita",
    "Ozaze\u002DZühara",
    "Pagola",
    "Santa Grazi",
    "Sarrikotapea",
    "Sohüta",
    "Urdiñarbe",
    "Zalgize\u002DDoneztebe",
    "Ürrüstoi\u002DLarrabile"
  ],
};

/**
 * Zuberera subdialect classification per Ahotsak (ahotsak.eus/euskalkiak/zuberotarra/).
 * Maps town name → subdialect. Used by the map tooltip.
 */
export const ZUERRERA_REGION = {
  // Basabürüa (upper Soule)
  "Aloze-Ziboze-Onizegaine": "Basabürüa",
  "Altzai-Altzabeheti-Zunharreta": "Basabürüa",
  "Altzürükü": "Basabürüa",
  "Arrokiaga": "Basabürüa",
  "Atharratze-Sorholüze": "Basabürüa",
  "Barkoxe": "Basabürüa",
  "Eskiula": "Basabürüa",
  "Etxebarre": "Basabürüa",
  "Gamere-Zihiga": "Basabürüa",
  "Garindaine": "Basabürüa",
  "Gotaine-Irabarne": "Basabürüa",
  "Hauze": "Basabürüa",
  "Idauze-Mendi": "Basabürüa",
  "Iruri": "Basabürüa",
  "Lakarri-Arhane-Sarrikotagaine": "Basabürüa",
  "Larraine": "Basabürüa",
  "Lexantzü-Zunharre": "Basabürüa",
  "Ligi-Atherei": "Basabürüa",
  "Liginaga-Astüe": "Basabürüa",
  "Mendikota": "Basabürüa",
  "Montori-Berorize": "Basabürüa",
  "Montori": "Basabürüa",
  "Muskildi": "Basabürüa",
  "Ozaze-Zühara": "Basabürüa",
  "Pagola": "Basabürüa",
  "Santa Grazi": "Basabürüa",
  "Urdatx / Santa Grazi": "Basabürüa",
  "Urdiñarbe": "Basabürüa",
  "Zalgize-Doneztebe": "Basabürüa",

  // Pettarrakoa (lower Soule)
  "Ainharbe": "Pettarrakoa",
  "Arüe-Ithorrotze-Olhaibi": "Pettarrakoa",
  "Berrogaine-Larüntze": "Pettarrakoa",
  "Bildoze-Onizepea": "Pettarrakoa",
  "Domintxaine-Berroeta": "Pettarrakoa",
  "Ezpeize-Ündüreine": "Pettarrakoa",
  "Jeztaze": "Pettarrakoa",
  "Lohitzüne-Oihergi": "Pettarrakoa",
  "Maule-Lextarre": "Pettarrakoa",
  "Mitikile-Larrori-Mendibile": "Pettarrakoa",
  "Ospitalepea": "Pettarrakoa",
  "Ozaraine-Erribareita": "Pettarrakoa",
  "Sarrikotapea": "Pettarrakoa",
  "Sohüta": "Pettarrakoa",
  "Ürrüstoi-Larrabile": "Pettarrakoa",
};
